siteTitle = "Jenessa White"
siteDescr = "Jenessa White's personal website that house a short bio, her skills, resume, and some of Jenessa's past work."
siteAuthor = "Jenessa White"

twitterId = "jnessview"
googleAnalyticsId = ""
linkPrefix = "/gatsby-starter-bootstrap"
